Set Shell zsh
Sleep 500ms
Require fzf
Sleep 500ms
Type "source ~/.zshrc"
Enter
Sleep 500ms
Type "aws:switch"
Enter
Sleep 1500ms
Type "main"
Sleep 1500ms
Enter
Sleep 500ms
Type "aws sts get-caller-identity"
Sleep 500ms
Enter
Sleep 500ms
Type "q"
Sleep 500ms
Escape
Sleep 500ms
Up
Sleep 500ms
Type " --ou"
Tab
Sleep 500ms
Type "json"
Enter
Sleep 500ms
Type "q"
Sleep 500ms
Escape
Up
Type " --no-c"
Tab 2
Sleep 1s
Tab 2
Enter 2
Sleep 500ms
Ctrl+D

